version: '3.3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql:5.7.28
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: hadid-karan
      MYSQL_USER: hadidkaran
      MYSQL_PASSWORD: hadidkaran
      MYSQL_ROOT_PASSWORD: hadi2400
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql
    networks:
      - laravel
