version: '3.3'

networks:
  laravel_network:

services:
    laravel_app:
      networks:
        - laravel_network
      depends_on:
        - db
      container_name: laravel-php
      image: lorisleiva/laravel-docker:7.4
      volumes:
          - ./:/var/www
      ports:
        - "8000:80"
      restart: always
      environment:
        DB_HOST: hadid-karan-db
        DB_PORT: 3306
        DB_DATABASE: hadid-karan
        DB_USERNAME: hadidkaran
        DB_PASSWORD: hadidkaran

    db:
      networks:
        - laravel_network
      container_name: hadid-karan-db
      image: mysql:5.7.28
      volumes:
          - ./mysql:/var/lib/mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: hadi2400
          MYSQL_DATABASE: hadid-karan
          MYSQL_USER: hadidkaran
          MYSQL_PASSWORD: hadidkaran
      ports:
          - 3306:3306

    # adminer:
    #     depends_on:
    #         - db
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080

